Update hr tool

diff --git a/scripts/hr/hr b/scripts/hr/hr
--- a/scripts/hr/hr
+++ b/scripts/hr/hr
@@ -1121,7 +1121,17 @@ update_opencog() {
 }
 
 update_hr() {
-    install_hr
+    local url=https://raw.githubusercontent.com/hansonrobotics/HEAD/master/scripts/hr/hr
+    local file=/tmp/hr
+    curl -sLo $file ${url}
+    bash_flag=$(file $file | grep bash | wc -l)
+    if [[ $bash_flag != "1" ]]; then
+        error "Can't get hr"
+        exit 1
+    fi
+    chmod +x /tmp/hr
+    /tmp/hr install hr
+    rm -f /tmp/hr
 }
 
 help_update() {
