Print colorful message on console

diff --git a/scripts/hrtool b/scripts/hrtool
--- a/scripts/hrtool
+++ b/scripts/hrtool
@@ -17,6 +17,20 @@ done
 
 OPENCOG_REPOS=(cogutils atomspace opencog ros-behavior-scripting relex)
 
+COLOR_INFO='\033[32m'
+COLOR_WARN='\033[33m'
+COLOR_ERROR='\033[31m'
+COLOR_RESET='\033[0m'
+info() {
+    printf "${COLOR_INFO}[INFO] ${1}${COLOR_RESET}\n"
+}
+warn() {
+    printf "${COLOR_WARN}[WARN] ${1}${COLOR_RESET}\n"
+}
+error() {
+    printf "${COLOR_ERROR}[ERROR] ${1}${COLOR_RESET}\n"
+}
+
 install_basic() {
     sudo apt-get -y update
     sudo apt-get -y install git
@@ -172,7 +186,7 @@ clone() {
     dest=${3-"."}/$repo
     # if ssh clone failed, then try https clone
     if [[ -d $dest ]]; then
-        echo "$dest already exists"
+        info "$dest already exists"
     else
         git clone git@github.com:$owner/$repo.git $dest || git clone https://github.com/$owner/$repo.git $dest
     fi
@@ -193,16 +207,16 @@ check_local_changes() {
             cd $HR_WORKSPACE/opencog/$repo
             branch=$(git rev-parse --abbrev-ref HEAD)
             if [[ $branch != 'master' ]]; then
-                echo "HEAD branch is not master $(pwd)" 1>&2
+                warn "HEAD branch is not master $(pwd)" 1>&2
                 return 1
             fi
             if [[ $(git status -uno --porcelain|wc -c) != 0 ]]; then
-                echo "Plese commit the change(s) $(pwd)" 1>&2
-                echo $(git status --porcelain) 1>&2
+                warn "Plese commit the change(s) $(pwd)" 1>&2
+                warn $(git status --porcelain) 1>&2
                 return 1
             fi
             if [[ $(git diff --name-only master origin/master|wc -c) != 0 ]]; then
-                echo "Master branch is not synchronized with origin $(pwd)" 1>&2
+                warn "Master branch is not synchronized with origin $(pwd)" 1>&2
                 return 1
             fi
         fi
@@ -217,7 +231,7 @@ update_opencog() {
         cd $HR_WORKSPACE/opencog/$repo
         branch=$(git rev-parse --abbrev-ref HEAD)
         if [[ $branch != $DEFAULT_BRANCH ]]; then
-            echo "[${repo}] Branch is not (${DEFAULT_BRANCH}) branch (${branch}). Skip."
+            warn "[${repo}] Branch is not (${DEFAULT_BRANCH}) branch (${branch}). Skip."
             continue
         fi
         git pull origin $DEFAULT_BRANCH
@@ -231,7 +245,7 @@ do_update_hr() {
         cd $HR_WORKSPACE/$repo
         branch=$(git rev-parse --abbrev-ref HEAD)
         if [[ $branch != $DEFAULT_BRANCH ]]; then
-            echo "[${repo}] Branch is not (${DEFAULT_BRANCH}) branch (${branch}). Skip."
+            warn "[${repo}] Branch is not (${DEFAULT_BRANCH}) branch (${branch}). Skip."
             continue
         fi
         git pull origin $DEFAULT_BRANCH
@@ -264,7 +278,7 @@ do_get_src() {
 do_dev_mode() {
     DOMAIN=${1-"opencog"}
     check_local_changes || exit 1
-    echo "Switching to $DOMAIN repositories"
+    warn "Switching to $DOMAIN repositories"
     for repo in ${OPENCOG_REPOS[*]}
     do
         cd $HR_WORKSPACE
@@ -381,7 +395,7 @@ check_ws() {
     local ws=$(readlink -f ${HR_WORKSPACE})
     if [[ $rel_ws != $ws ]]; then
         local confirm
-        printf "WARN: the workspace configured ${ws} doesn't match the your working path ${rel_ws}\n"
+        warn "The workspace configured ${ws} doesn't match the your working path ${rel_ws}"
         _get_confirm "Continue using ${ws}?"
         [[ ${confirm} -eq 1 ]] || exit 0
     fi
